### Mann Whitney U test
Непараметрический тест, который используется для сравнения двух независимых выборок. Он помогает определить, есть ли статистически значимые различия между двумя группами. Этот тест часто применяется в случаях, когда данные не соответствуют нормальному распределению, когда размеры выборок малы, или при ординальных данных.

Нулевая гипотеза (H0): Распределения двух групп идентичны (или, эквивалентно, медианы двух групп равны).<br>
Альтернативная гипотеза (H1): Распределения двух групп различны (или медианы двух групп различны).

Сначала ранжируются все данные, объединенные из обеих групп (Ранжирование может быть выполнено с учетом повторяющихся значений).<br>
Затем вычисляется сумма рангов для каждой группы.<br>
Используя сумму рангов, рассчитывается статистика U, которая указывает на степень различия между группами.

<img src="data/u_test.png" alt="" width="400"/>

<img src="data/u_to_z.png" alt="" width="400"/>

#### Пример задачи
У нас есть оценки удовлетворенности клиентов из двух разных регионов, и мы хотим определить, существует ли значительная разница в уровнях удовлетворенности между этими двумя регионами.

In [ ]:
import numpy as np
from scipy.stats import mannwhitneyu

In [ ]:
# Назначаем random seed
np.random.seed(105)

# Синтезируем данный для Региона А
region_a = np.append(np.random.randint(1, 4, 25), np.random.randint(4, 6, 25))

# Синтезируем данный для Региона B
region_b = np.append(np.random.randint(1, 4, 18), np.random.randint(4, 6, 32))

In [ ]:
# Проводим Mann Whitney test
u_statistic, p_value = mannwhitneyu(region_a, region_b, alternative='less')

In [ ]:
# Смотрим результаты
print("\nMann-Whitney U тест результаты:")
print("U Statistic:", u_statistic)
print("P-Value:", p_value)

In [ ]:
# Интерпретация
alpha = 0.1
if p_value < alpha:
    print("\nВывод: существует значительная разница в показателях удовлетворенности между регионом А и регионом Б.")
else:
    print("\nВывод: существенной разницы в показателях удовлетворенности между регионом А и регионом Б нет.")

### Kolmogorov-Smirnov test
Статистический тест, который используется для проверки того, насколько хорошо распределение данных соответствует теоретически предполагаемому распределению. Тест помогает определить, насколько эмпирическое распределение данных отличается от теоретического распределения (например, нормального распределения) или проверить, совпадают ли два эмпирических распределения.

**One-sample test**<br>
<img src="data/KS1.png" alt="One-sample test" width="500"/>

In [1]:
from scipy.stats import kstest
import numpy as np

In [2]:
np.random.seed(105)
sample = np.random.normal(loc=0, scale=1, size=100)

In [3]:
ks_statistic, p_value = kstest(sample, 'norm')

In [4]:
print(f"KS Statistic: {ks_statistic}")
print(f"P-value: {p_value}")

KS Statistic: 0.09145904750849598
P-value: 0.3514822670420972

**Two-sample test**<br>
<img src="data/KS2.png" alt="One-sample test" width="500"/>

In [5]:
from scipy.stats import ks_2samp
import numpy as np

In [10]:
np.random.seed(105)
sample1 = np.random.normal(loc=0, scale=1, size=400)
sample2 = np.random.normal(loc=0, scale=1, size=500)

In [11]:
ks_statistic, p_value = ks_2samp(sample1, sample2)

In [12]:
print(f"KS Statistic: {ks_statistic}")
print(f"P-value: {p_value}")

KS Statistic: 0.054
P-value: 0.5189643025398532

### Shapiro-Wilk test
статистический тест, который используется для проверки гипотезы о нормальности распределения данных. Другими словами, он помогает определить, насколько хорошо данные следуют нормальному распределению.

<img src="data/shapiro.png" alt="One-sample test" width="500"/>

In [14]:
import numpy as np
from scipy.stats import shapiro

In [15]:
data = np.array([2.3, 2.5, 2.7, 3.0, 3.1, 3.4, 3.6, 3.8, 4.0, 4.1])

In [16]:
statistic, p_value = shapiro(data)

In [17]:
print("Shapiro-Wilk Test Statistic:", statistic)
print("P-Value:", p_value)

Shapiro-Wilk Test Statistic: 0.9522241353988647
P-Value: 0.6948529481887817

In [18]:
alpha = 0.05
if p_value > alpha:
    print("Не удалось отклонить null hypohtesis - дата распределена нормально")
else:
    print("Отклоняем null hypothesis - дата не распределена нормально")

Не удалось отклонить null hypohtesis - дата распределена нормально

### Wilcoxon test

непараметрический статистический тест, используемый для сравнения связанных (зависимых) выборок. Он проверяет, отличается ли медианная разница между парными наблюдениями от нуля. Работает с ординальными значениями

Нулевая гипотеза (H0): Медианная разница между парными наблюдениями равна нулю.<br>
Альтернативная гипотеза (H1): Медианная разница не равна нулю (двусторонний тест) или больше/меньше нуля (односторонний тест).

Алгоритм просчета:
* для кажой пары считаем абсолютную разницу
* ранжируем получившиеся разницы, присваевам ранг
* считаем сумму положительных и отрицательных рангов
* считаем W статистику и стандартное отколнение
* получивашиеся статитсики можно применить для нормального распределения (при достаточно большой выборке n>25)
* при маленькой выборке используются табличные (имперические) значения
* стандартное отклонение корректируется при одинковых значениях в двух выборках

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import wilcoxon
from scipy.stats import norm

In [3]:
np.random.seed(116)
sample_pd = pd.DataFrame({'val1': np.random.randint(20, 30, 30),
                          'val2': np.random.randint(21, 31, 30)}
                        )
sample_pd.head()

   val1  val2
0    25    24
1    26    28
2    21    24
3    22    27
4    21    26

In [4]:
#вычисление разности
sample_pd['diff'] = sample_pd.apply(lambda x: x['val2'] - x['val1'], axis=1)
sample_pd.head()

   val1  val2  diff
0    25    24    -1
1    26    28     2
2    21    24     3
3    22    27     5
4    21    26     5

In [5]:
#вычисление абсолютной разницы
sample_pd['abs_diff'] = abs(sample_pd['diff'])
sample_pd.head()

   val1  val2  diff  abs_diff
0    25    24    -1         1
1    26    28     2         2
2    21    24     3         3
3    22    27     5         5
4    21    26     5         5

In [6]:
#арнжирование абсолютных значений
sample_pd['rank'] = sample_pd['abs_diff'].rank(method='average', ascending=False)
sample_pd.head()

   val1  val2  diff  abs_diff  rank
0    25    24    -1         1  25.5
1    26    28     2         2  20.5
2    21    24     3         3  14.5
3    22    27     5         5   7.0
4    21    26     5         5   7.0

In [7]:
#сумма положительных рангов
w_pos = sample_pd[sample_pd['diff']>0]['rank'].sum()
w_pos

264.5

In [8]:
#сумма негативных рангов
w_neg = sample_pd[sample_pd['diff']<0]['rank'].sum()
w_neg

113.5

In [9]:
#w статистика - это наименьшее из двух статистик
w = min(w_pos, w_neg)
w

113.5

In [10]:
#повторяющиеся значения
(sample_pd
 .groupby('diff', as_index=False)
 .agg(cnt = ('rank', 'count'))
)

    diff  cnt
0     -7    1
1     -4    1
2     -3    2
3     -2    1
4     -1    2
5      0    3
6      1    2
7      2    5
8      3    4
9      4    2
10     5    3
11     6    1
12     7    2
13    10    1

In [11]:
sample_pd.shape

(30, 5)

In [12]:
# #стандартное отколнение
n = 30
t2 = 2
t4 = 2
t6 = 2
t7 = 5
t8 = 4
t9 = 2
t10 = 3
t12 = 2
std = np.sqrt(n * (n + 1) * (2*n + 1) / 24 - 
              t2 * (t2 - 1) * (2*t2 + 1) / 24 -
              t4 * (t4 - 1) * (2*t4 + 1) / 24 -
              t6 * (t6 - 1) * (2*t6 + 1) / 24 -
              t7 * (t7 - 1) * (2*t7 + 1) / 24 -
              t8 * (t8 - 1) * (2*t8 + 1) / 24 -
              t9 * (t9 - 1) * (2*t9 + 1) / 24 -
              t10 * (t10 - 1) * (2*t10 + 1) / 24 -
              t12 * (t12 - 1) * (2*t12 + 1) / 24)
std

48.438104834933426

In [14]:
#W при нулевой гипотезе
W_mean = n * (n+1) / 4
W_mean

232.5

In [15]:
#считаем Z статистику
z = (w - W_mean) / std
z

-2.4567435164015237

In [16]:
#считаем вероятность p
p = 2 * (1 - norm.cdf(abs(z)))
p

0.014020274456974624

In [17]:
stat, p = wilcoxon(sample_pd['val1'], sample_pd['val2'])
stat, p

C:\llallo\Python\Lib\site-packages\scipy\stats\_morestats.py:3414: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "

(82.5, 0.010252438939021303)